### ISSUE TITLE
Using npm packages in angular site

### ISSUE THREAD

**Issue by caspian154** [caspian154/beer-shelf#2]
font-awesome is installed via `npm insall font-awesome -s`, what is the best way to reference that from the angular public "app"?

**Comment by mdw7326** [comment]
I don't know if this helps, but in my  [OpenBrews](https://github.com/OpenBrews/OpenBrews) project, I use npm for development tools/server stuff, and bower to install js/css libraries. Then I can set the bower directory in a `.bowerrc` file like so:

```
#.bowerrc
{
  "directory": "openbrews/lib"
}
```

**Comment by caspian154** [comment]
Sweet - that probably works. I didn't use bower yet, but I figured it was one of the things I should do next.

**Comment by fostertheweb** [comment]
Try [unpkg](https://unpkg.com/#/) for front-end dependencies

**Comment by mdw7326** [comment]
ooooh Ya you should try that

**Comment by caspian154** [comment]
Done.
