### ISSUE TITLE
How do I make a user to log in with?

### ISSUE THREAD

**Issue by mdw7326** [caspian154/beer-shelf#7]
I can run the app, and see the login screen. How do I initialize a user to log in with though?

**Comment by caspian154** [comment]
Did you create the database? The first user has to be manually created in the database.

**Comment by mdw7326** [comment]
No :( What do I do to create the database?

**Comment by caspian154** [comment]
You'll need a database - I used MySQL. The connection settings are in `/database.js`. I have sql scripts in the `/database` folder. Sorry it's not very automated and clean. I wanted to focus on learning angular and node. I intend to get around to the setup and that type of stuff eventually.
